#!/usr/bin/env bash

set -e

cd "$(dirname $0)"

SYSTEM='/etc/nixos'
LOCAL="$HOME/.config/nixpkgs"

sudo git -C "$SYSTEM" fetch
if $(sudo git -C "$SYSTEM" rev-parse HEAD) != $(sudo git -C "$SYSTEM" rev-parse @{u})
then
    sudo git -C "$SYSTEM" pull
    sudo nixos-rebuild switch
fi

dconf dump / | dconf2nix > "$LOCAL/dconf.nix"

git -C "$LOCAL" fetch
if $(git -C "$LOCAL" rev-parse HEAD) != $(git -C "$LOCAL" rev-parse @{u})
then
    git -C "$LOCAL" pull
    home-manager switch
fi
